"""Professional PDF report generation for AgriGuard AI."""

from datetime import datetime
from io import BytesIO
from uuid import uuid4
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

FOOTER_TEXT = "Generated by AgriGuard AI \u2013 Educational Use Only"


def _safe_text(value):
    """Escape report text for ReportLab paragraph rendering."""
    if value is None or str(value).strip() == "":
        return "Not available."

    return escape(str(value).strip()).replace("\n", "<br/>")


def _add_section(content, styles, title, value):
    content.append(Paragraph(title, styles["AgriSectionHeading"]))
    content.append(Paragraph(_safe_text(value), styles["BodyText"]))
    content.append(Spacer(1, 10))


def _build_styles():
    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="AgriTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            textColor=colors.HexColor("#1f7a3f"),
            spaceAfter=14,
        )
    )
    styles.add(
        ParagraphStyle(
            name="AgriSubtitle",
            parent=styles["BodyText"],
            fontSize=10,
            textColor=colors.HexColor("#4a4a4a"),
            spaceAfter=16,
        )
    )
    styles.add(
        ParagraphStyle(
            name="AgriSectionHeading",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            textColor=colors.HexColor("#22543d"),
            spaceBefore=8,
            spaceAfter=6,
        )
    )
    return styles


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#555555"))
    canvas.drawCentredString(A4[0] / 2, 0.35 * inch, FOOTER_TEXT)
    canvas.restoreState()


def generate_pdf_report(report_data):
    """Generate a downloadable AgriGuard AI disease report.

    Parameters
    ----------
    report_data : dict
        Standard report fields (disease_name, confidence_score, cause, etc.).
        Optionally includes ``advisor_data`` dict with keys:
            prevention, sustainability, treatment_strategy
        When ``advisor_data`` is present an "AI Advisor Summary" section is
        appended at the end of the report.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.55 * inch,
        leftMargin=0.55 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.7 * inch,
    )
    styles = _build_styles()
    content = []

    report_id = report_data.get("report_id") or f"AGR-{uuid4().hex[:8].upper()}"
    generated_at = report_data.get("generated_at") or datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    content.append(Paragraph("AgriGuard AI", styles["AgriTitle"]))
    content.append(
        Paragraph(
            "Sustainable Agriculture Decision Support System",
            styles["AgriSubtitle"],
        )
    )

    def value_cell(value):
        return Paragraph(_safe_text(value), styles["BodyText"])

    summary_table = Table(
        [
            ["Report ID", value_cell(report_id)],
            ["Date and Time", value_cell(generated_at)],
            ["Disease Name", value_cell(report_data.get("disease_name"))],
            ["Confidence Score", value_cell(report_data.get("confidence_score"))],
            [
                "Sustainability Score",
                value_cell(report_data.get("sustainability_score")),
            ],
        ],
        colWidths=[1.8 * inch, 4.8 * inch],
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f5ee")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1f5132")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cfd8d3")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    content.append(summary_table)
    content.append(Spacer(1, 12))

    # Required report sections.
    _add_section(content, styles, "Cause", report_data.get("cause"))
    _add_section(content, styles, "Symptoms", report_data.get("symptoms"))
    _add_section(content, styles, "Medication", report_data.get("medication"))
    _add_section(content, styles, "Treatment", report_data.get("treatment"))
    _add_section(
        content,
        styles,
        "Sustainability Advice",
        report_data.get("sustainability_advice"),
    )
    _add_section(
        content,
        styles,
        "Prevention Tips",
        report_data.get("prevention_tips"),
    )

    # ------------------------------------------------------------------
    # AI Advisor Summary — included only when advisor data is available.
    # This section is generated by the ai_advisor module and added to
    # every PDF report after a disease is detected.
    # ------------------------------------------------------------------
    advisor_data = report_data.get("advisor_data")
    if advisor_data:
        content.append(Spacer(1, 6))
        content.append(
            Paragraph("AI Advisor Summary", styles["AgriSectionHeading"])
        )
        content.append(
            Paragraph(
                "The following advisory was automatically generated by AgriGuard AI "
                "based on the detected disease. Always consult local agricultural "
                "experts before applying chemicals or changing farming practices.",
                styles["BodyText"],
            )
        )
        content.append(Spacer(1, 8))

        _add_section(
            content,
            styles,
            "AI Prevention Tip",
            advisor_data.get("prevention"),
        )
        _add_section(
            content,
            styles,
            "AI Sustainability Advice",
            advisor_data.get("sustainability"),
        )
        _add_section(
            content,
            styles,
            "AI Treatment Strategy",
            advisor_data.get("treatment_strategy"),
        )

    doc.build(content, onFirstPage=_footer, onLaterPages=_footer)
    buffer.seek(0)
    return buffer


# Backward-compatible alias for older imports.
generate_pdf = generate_pdf_report
